### ISSUE TITLE
Improve memory allocation for MifareDESFireKeys

### ISSUE THREAD

**Issue by GoogleCodeExporter** [nfc-tools/libfreefare#21]
I'm currently writing Go bindings for the libfreefare.

Go provides garbage collection, Go programmers expect that objects which aren't tied to external resources do not need explicit deinitialization. A MifareDESFireKey is such an object. It contains a key used for initialization. As far as I am concerned, a MifareDESFireKey does not allocate any resources and can be free'd at any time.

Right now, MifareDESFireKeys are allocated by the libfreefare using malloc() and free(). This makes it very hard to give control over allocation to a garbage collector: You need two layers of wrapping which causes performance loss and an unneccessary amount of extra garbage to be allocated. Library support is needed to be able to control the allocation of MifareDESFireKeys.

I request to implement one of the following things:

1. Completely define struct mifare_desfire_key in freefare.h and for each function　mifare_desfire_*_key_new() provide an additional mifare_desfire_*_key_init() with the same effect, except that you explicitly pass a MifareDESFireKey.
2. Provide a function mifare_desfire_key_sizeof() that returns sizeof(struct mifare_desfire_key_sizeof) and otherwise proceed as in 1).
3. For each function mifare_desfire_*_key_new() provide an additional mifare_desfire_*_key_custom_new() with an extra parameter`void *(*alloc)(size_t size)` to pass a custom memory allocation routine. Albeit not perfect, this would already simplify allocation control by a big deal. What is missing is the ability to embed a MifareDESFireKey into a custom Go struct to save even more space.

Original issue reported on code.google.com by `fuz...@gmail.com` on 25 Feb 2014 at 12:58

**Comment by smortex** [comment]
@fuzxxl I guess you originally opened this issue on Google Code.

I don't really understand the problem, so I will reformulate what I understood and explain what are my concerns with these proposed solutions. Please tell me if I am wrong: I have difficulties to see what is the problem you want to solve.

----

> :one:  Completely define struct mifare_desfire_key in freefare.h and for each function　mifare_desfire_key_new() provide an additional mifare_desfire_key_init() with the same effect, except that you explicitly pass a MifareDESFireKey.

The idea of the opaque type is precisely to avoid the structure manipulation from the outside. Therefore I am not willing to move the struct in `freefare.h` :frowning:

----

> :two:  Provide a function mifare_desfire_key_sizeof() that returns sizeof(struct mifare_desfire_key_sizeof) and otherwise proceed as in 1).

Do you mean a new public API function like this:

~~~c
int
mifare_desfire_key_size (void) {
    return sizeof (struct mifare_desfire_key);
}
~~~
so that the Go interpreter can allocate chucks of the right size itself (gasp) and then use another new API function to fill-in the allocated memory with proper data, such as:

~~~c
void
mifare_desfire_key_init (struct mifare_desfire_key *key, int key_type, void *data)
{
    size_t n = key_size (key_type);
    memcpy (key->data, data, n);
    update_key_schedules (key);
}
~~~

This mean let the Go bindings the responsibility to handle the key version stuff (Or add some more API functions for this purpose).

Cluttering the API with function only useful for the bindings looks like a bag idea as far as I am concerned :frowning:.

----

> :three: For each function mifare_desfire_key_new() provide an additional mifare_desfire_key_custom_new() with an extra parameter `void *(*alloc)(size_t size)` to pass a custom memory allocation routine. Albeit not perfect, this would already simplify allocation control by a big deal. What is missing is the ability to embed a MifareDESFireKey into a custom Go struct to save even more space.

I have the same feeling as the previous solution: it clutters the API and looks ugly :fearful:.

----

As far as I can see, the "philosophy" of keys management is very similar to the one of tags management, or at least I hope it to be.  Can you please give us some insights about what makes key management in the go bindings different than the tags bindings?

**Comment by fuzxxl** [comment]
This problem has become obsolete because the desired mechanism of memory allocation (i.e. allocate all the memory on the Go side) has been forbidden by the Go team. There is no need to do any additional work.

**Comment by smortex** [comment]
Okay, thank you for the feedback
