### ISSUE TITLE
mifare-classic-read-ndef slow

### ISSUE THREAD

**Issue by DHoffm** [nfc-tools/libfreefare#59]
I tested the library with a mifare 1k card and noticed that the following call took around 20 seconds to finally grab all ndef data.

`mifare-classic-read-ndef -y -o data.mdf`

Is this the normal behaviour or is there a way to speed things up?

I'm running the library on Raspbian.

**Comment by smortex** [comment]
Nope, this should be ways faster.

```
romain@marvin ...s/nfc-tools/libfreefare/build % git rev-parse HEAD
565ee18b8e19e01d73c1dd4b2cacdc1c877017b2
romain@marvin ...s/nfc-tools/libfreefare/build % time ./examples/mifare-classic-read-ndef -yo data.mdf  
Found Mifare Classic 1k with UID 6c185fd3. 
NFC Forum application contains a "NDEF Message TLV".
./examples/mifare-classic-read-ndef -yo data.mdf  0,00s user 0,01s system 2% cpu 0,257 total
```

You can try to swap the NFC device, card and computer to see which one is the bottleneck.

Since the problem should be on your side, I close this issue.  If you discover something interesting, please comment here to share what you learned.  In case there is something we can do to improve the situation, we will re-open this issue to address it.

Thanks!
